import { Platform, StyleSheet, Dimensions } from "react-native";
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from "react-native-responsive-dimensions";
import { textColor, appColor, buttonColor } from "../../../../constants/colors";
import { fontFamily } from "../../../../constants/fonts";
const windowHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: textColor.white,
  },
  image: {
    height: responsiveHeight(10),
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    resizeMode: "contain",
  },
  txt: {
    fontSize: responsiveFontSize(2),
    fontFamily: fontFamily.appTextMedium,
    color: textColor.white,
  },
  map: {
    height: responsiveHeight(15),
    width: responsiveWidth(80),
    alignSelf: "center",
  },
  locationview: {
    width: responsiveWidth(90),
    alignSelf: "center",
    backgroundColor: textColor.white,
    borderWidth: responsiveWidth(0.3),
    borderColor: textColor.lightgrey,
    marginTop: responsiveHeight(1),
    borderRadius: responsiveWidth(4),
    paddingBottom: responsiveHeight(2),
  },
  locatontxt: {
    color: textColor.secondary,
    fontFamily: fontFamily.appTextBold,
    marginLeft: responsiveWidth(4),
    marginTop: responsiveHeight(1),
  },
  gamebtnheader: {
    backgroundColor: textColor.white,
    width: responsiveWidth(90),
    borderRadius: responsiveWidth(4),
    alignSelf: "center",
    marginTop: responsiveHeight(1),
    borderWidth: responsiveWidth(0.3),
    borderColor: textColor.lightgrey,
  },
  gamebtn: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: responsiveWidth(3),
    borderBottomWidth: responsiveWidth(0.3),
    borderBottomColor: textColor.lightgrey,
    alignItems: "center",
  },
  heading: {
    marginLeft: responsiveWidth(5),
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(2),
    marginBottom: responsiveHeight(1),
  },
  heading4: {
    marginLeft: responsiveWidth(5),
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(4),
    marginBottom: responsiveHeight(3),
  },

  heading1: {
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2),
    marginTop: responsiveHeight(2),
    marginBottom: responsiveHeight(1),
  },
  intrestbtnheader: {
    flexDirection: "row",
    width: responsiveWidth(90),
    alignSelf: "center",
    marginBottom:
      Platform.OS === "android" ? responsiveHeight(1) : responsiveHeight(2),
  },
  malebtn: {
    backgroundColor: buttonColor.grey,
    padding: responsiveWidth(3),
    borderRadius: responsiveWidth(4),
    width: responsiveWidth(40),
    padding: 0,
    margin: 0,
    justifyContent: "center",
    alignItems: "center",
    height:
      Platform.OS === "android" ? responsiveHeight(6) : responsiveHeight(6),
  },
  resetbtn: {
    width: responsiveWidth(90),
    height: responsiveHeight(7),
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(5),
    backgroundColor: buttonColor.grey,
    marginVertical: responsiveHeight(1),
  },
  resetbtn1: {
    backgroundColor: textColor.secondary,
    width: responsiveWidth(90),
    height: responsiveHeight(7),
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(5),
  },
  resetbtnheader: {
    // flexDirection: "row",
    // justifyContent: "space-between",
    width:
      Platform.OS === "android" ? responsiveWidth(85) : responsiveWidth(90),
    alignSelf: "center",
    marginTop: responsiveHeight(2),
    alignItems: "center",
    justifyContent: "center",
  },
  resetbtntxt: {
    fontFamily: fontFamily.appTextMedium,
    color: "white",
    fontSize: responsiveFontSize(2.4),
  },
  resetbtntxt2: {
    color: "#8c8c8c",
    fontFamily: fontFamily.appTextRegular,
    fontSize: responsiveFontSize(2.3),
  },
  distanceView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  distanceVal: {
    marginTop: responsiveHeight(1),
    flexDirection: "row",
    marginRight: responsiveWidth(2),
  },
  distanceWrapper: {
    width: responsiveWidth(90),
    alignSelf: "center",
    // backgroundColor: "red",
    flexDirection: "row",
    alignItems: "center",
  },
  wrapper1: {
    width: responsiveWidth(65),
  },
  ageView: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  mainWrapper: {
    width: responsiveWidth(90),
    alignSelf: "center",
  },
  ageText: {
    marginTop: responsiveHeight(2.5),
    color: textColor.secondary,
    marginRight: responsiveWidth(5),
  },
  checkedView: {
    width: responsiveWidth(25),
    backgroundColor: textColor.secondary,
    marginTop: responsiveHeight(4),
    height:
      Platform.OS === "android" ? responsiveHeight(6) : responsiveHeight(6),
    borderRadius: responsiveWidth(4),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: responsiveWidth(3),
    bottom: responsiveHeight(1),
  },
  genderCheckedView: {
    width: responsiveWidth(40),
    backgroundColor: textColor.secondary,
    height:
      Platform.OS === "android" ? responsiveHeight(6) : responsiveHeight(6),
    // marginTop: responsiveHeight(3),
    borderRadius: responsiveWidth(4),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginLeft: responsiveWidth(4),
    padding: 0,
    margin: 0,
  },
  anyTxt: {
    color: "white",
    fontFamily: fontFamily.appTextMedium,
    marginVertical: responsiveHeight(1),
  },
  anyTxt2: {
    color: "black",
    fontFamily: fontFamily.appTextMedium,
    marginVertical: responsiveHeight(1),
  },
  anyUnchecked: {
    backgroundColor: buttonColor.grey,
    paddingHorizontal: responsiveWidth(2),
    borderRadius: responsiveWidth(4),
    height:
      Platform.OS === "android" ? responsiveHeight(6) : responsiveHeight(6),
    width: responsiveWidth(25),
    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
    marginTop: responsiveHeight(4),
    bottom: responsiveHeight(1),
  },
  Modalbg2: {
    height: Platform.OS === "ios" ? responsiveHeight(90) : responsiveHeight(95),
    width: responsiveWidth(95),
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: Platform.OS === "ios" ? responsiveHeight(2) : null,

    // backgroundColor: "transparent",
    // borderRadius:responsiveWidth(10),
    // marginLeft: responsiveWidth(5),
  },
  boostTxt: {
    width: responsiveWidth(80),
    bottom: responsiveHeight(4),
    // backgroundColor:'green',
    // alignSelf: "center",
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2.3),
    textAlign: "center",
  },
  btnGroup: {
    width: "95%",
    alignSelf: "center",
    // backgroundColor: "yellow",
    position: "absolute",
    // bottom: r(10.3),
    top: windowHeight * 0.6,
    justifyContent: "center",
  },
  yesBtn: {
    backgroundColor: textColor.secondary,
    width: "70%",
    height: responsiveHeight(7),
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(5),
  },
  yesBtn1: {
    backgroundColor: textColor.secondary,
    width: responsiveWidth(60),
    height: responsiveHeight(6),
    justifyContent: "center",
    alignItems: "center",
    // marginRight: responsiveWidth(3),
    borderRadius: responsiveWidth(5),
  },
  yesTxt: {
    fontFamily: fontFamily.appTextMedium,
    color: "white",
    fontSize: responsiveFontSize(2.4),
  },
  noTxt: {
    fontFamily: fontFamily.appTextMedium,
    color: "#8c8c8c",
    fontSize: responsiveFontSize(2.2),
  },
  noBtn: {
    width: responsiveWidth(70),
    height: responsiveHeight(8),
    // backgroundColor:'red',
    top: responsiveHeight(0.6),
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: responsiveWidth(5),
  },
});
