/** @format */

import {
  appColor,
  buttonColor,
  textColor,
  theamColor,
} from "../../../../constants/colors";
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from "react-native-responsive-dimensions";
import { Platform, StyleSheet } from "react-native";
import { fontFamily } from "../../../../constants/fonts";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    paddingTop: Platform.OS === "ios" ? responsiveHeight(5) : 0,
  },
  header: {
    width: responsiveWidth(100),
    backgroundColor: textColor.white,
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    paddingTop: responsiveHeight(2),
    paddingBottom: responsiveHeight(2),
    paddingLeft: responsiveWidth(4),
    borderBottomWidth: responsiveWidth(0.05),
    borderBottomColor: "rgba(0,0,128,0.3)",
    marginRight: responsiveWidth(7),
    zIndex: 500,
  },
  user2: {
    height: responsiveWidth(13),
    width: responsiveWidth(13),
    borderRadius: responsiveWidth(13 / 2),
    marginLeft: responsiveWidth(2),
  },
  user4: {
    height: responsiveWidth(9),
    width: responsiveWidth(9),
    borderRadius: responsiveWidth(9 / 2),
    marginHorizontal: responsiveWidth(0.5),
  },
  circle: {
    alignItems: "center",
    justifyContent: "center",
    right: 9,
    bottom: responsiveWidth(1),
    width: responsiveWidth(10),
    height: responsiveWidth(10),
    borderRadius: responsiveWidth(10 / 2),
    backgroundColor: textColor.white,
  },
  list: {
    paddingHorizontal: 17,
    height: responsiveHeight(73),
  },
  footer: {
    flexDirection: "row",
    width: responsiveWidth(100),
    height: responsiveHeight(8.5),
    // height: 60,
    backgroundColor: "white",
    borderTopWidth: responsiveWidth(0.3),
    borderTopColor: textColor.lightgrey,
    paddingHorizontal: 10,
    padding: 5,
    alignSelf: "center",
    marginBottom: Platform.OS === "ios" ? 0 : 10,
  },
  btnSend: {
    backgroundColor: textColor.white,
    width: 40,
    height: 40,
    borderRadius: 360,
    alignItems: "center",
    justifyContent: "center",
  },
  iconSend: {
    width: 30,
    height: 30,
    alignSelf: "center",
  },
  inputContainer: {
    borderBottomColor: "#F5FCFF",
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    borderBottomWidth: 1,
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    marginRight: 10,
  },
  inputs: {
    height: 40,
    color: "black",
    marginLeft: 16,
    borderBottomColor: "#FFFFFF",
    alignSelf: "flex-end",
    width: responsiveWidth(70),

    // margin:0,
    // padding:0
  },
  balloon: {
    padding: 15,
    borderRadius: 20,
    backgroundColor: textColor.lightgrey,
  },
  itemIn: {
    alignSelf: "flex-start",
    marginTop: responsiveHeight(0.5),
  },
  itemOut: {
    alignSelf: "flex-end",
    marginTop: responsiveHeight(0.5),
  },
  time: {
    alignSelf: "flex-end",
    margin: 15,
    fontSize: 12,
    color: "#808080",
  },
  item: {
    marginVertical: 14,
    flex: 1,
    borderRadius: 300,
    padding: 5,
  },
  rbsheetbtn: {
    height: responsiveHeight(9),
    // justifyContent: "center",
    paddingLeft: responsiveWidth(5),
    // borderTopWidth: responsiveWidth(0.1),
    // borderTopColor: textColor.lightgrey,
    flexDirection: "row",
    alignSelf: "flex-start",
    alignItems: "center",
  },
  draggableIcon: {
    width: responsiveWidth(40),
    height: responsiveHeight(1),
    backgroundColor: textColor.lightgrey,
    alignSelf: "center",
    borderRadius: responsiveWidth(4),
    marginTop: responsiveHeight(1),
    marginBottom: responsiveHeight(2),
  },
  rbsheetbtntxt: {
    fontSize: responsiveFontSize(2),
    fontFamily: fontFamily.appTextRegular,
  },
  txtView: {
    borderBottomWidth: responsiveWidth(0.2),
    borderBottomColor: textColor.lightgrey,
    paddingBottom: responsiveHeight(2.2),
    width: responsiveWidth(75),
    marginLeft: responsiveWidth(4),
  },
  rbsheetbtntxt2: {
    fontSize: responsiveFontSize(2),
    fontFamily: fontFamily.appTextRegular,
    marginLeft: responsiveWidth(4),
    // borderBottomWidth: responsiveWidth(0.2),
    // borderBottomColor: textColor.lightgrey,
    paddingBottom: responsiveHeight(2.5),
    width: responsiveWidth(75),
  },
  unMatchText: {
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2),
    textAlign: "center",
    alignSelf: "center",
    color: textColor.primary,
  },
  btnGroup: {
    flexDirection: "row",
    width: responsiveWidth(90),
    alignSelf: "center",
    // backgroundColor: "red",

    justifyContent: "center",
    marginTop: responsiveHeight(2),
  },
  noBtn: {
    backgroundColor: buttonColor.grey,
    width: responsiveWidth(30),
    height: responsiveHeight(6),
    justifyContent: "center",
    alignItems: "center",
    marginRight: responsiveWidth(3),
    borderRadius: responsiveWidth(5),
  },
  yesBtn: {
    backgroundColor: textColor.secondary,
    width: responsiveWidth(30),
    height: responsiveHeight(6),
    justifyContent: "center",
    alignItems: "center",
    // marginRight: responsiveWidth(3),
    borderRadius: responsiveWidth(5),
  },
  yesTxt: {
    fontFamily: fontFamily.appTextBold,
    color: "white",
  },
  noTxt: {
    fontFamily: fontFamily.appTextBold,
  },
  subContainer: {
    backgroundColor: "#fff",
    elevation: 10,
    flex: 0.9,
    borderTopEndRadius: responsiveWidth(9),
    borderTopStartRadius: responsiveWidth(9),
  },
  tipview: {
    flexDirection: "row",
    backgroundColor: textColor.white,
    width: responsiveWidth(40),
    justifyContent: "space-around",
    borderRadius: responsiveWidth(4),
    padding: responsiveHeight(1.1),
    // top:responsiveHeight(1),
    position: "absolute",
    bottom: responsiveHeight(5),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  circle1: {
    height: responsiveWidth(5),
    width: responsiveWidth(5),
    borderRadius: responsiveWidth(5 / 2),
    backgroundColor: textColor.white,
    position: "absolute",
    alignSelf: "flex-end",
    alignItems: "center",
    justifyContent: "center",
    marginTop: responsiveHeight(4),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  SafetyText: {
    fontFamily: fontFamily.appTextBold,
    textAlign: "center",
    fontSize: responsiveFontSize(2.5),
  },
  orangeCircle: {
    // borderColor: "orange",
    // borderWidth: responsiveWidth(0.5),
    height: responsiveWidth(7.5),
    width: responsiveWidth(7.5),
    borderRadius: responsiveWidth(7.5 / 2),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "orange",
    bottom: responsiveHeight(1),
  },
  topflatlistview: {
    // marginTop: responsiveHeight(2),
    marginLeft: responsiveWidth(2),
  },
  card: {
    backgroundColor: textColor.white,
    height: responsiveWidth(6),
    width: responsiveWidth(6),
    borderRadius: responsiveWidth(6 / 2),
    marginBottom: responsiveHeight(0.5),
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  image: {
    height: responsiveWidth(17),
    width: responsiveWidth(17),
    alignItems: "flex-end",
    justifyContent: "flex-end",
  },
  backstyle: {
    borderRadius: responsiveWidth(25 / 2),
    // shadowColor: "#000",
    // shadowOffset: {
    //     width: 0,
    //     height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 3.84,
    // elevation: 5,
  },
  lipsimage: {
    height: responsiveWidth(4),
    width: responsiveWidth(4),
  },
});
