import React from "react";
import { Platform, StyleSheet, Dimensions } from "react-native";
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from "react-native-responsive-dimensions";
import {
  bggradientColor,
  buttonColor,
  gradientColor,
  textColor,
} from "../../../constants/colors";
import { fontFamily } from "../../../constants/fonts";
const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: bggradientColor.c1,
  },
  ringbtnimage: {
    height: responsiveHeight(3),
    width: responsiveWidth(5),
    resizeMode: "contain",
  },
  ringbtnimage2: {
    height: responsiveHeight(3),
    width: responsiveWidth(5),
    resizeMode: "contain",
  },
  ringbtntxt: {
    marginLeft: responsiveWidth(1),
    fontSize: responsiveFontSize(2.1),
  },
  nameview: {
    flexDirection: "row",
    paddingLeft: responsiveWidth(3),
    // backgroundColor:'red',
  },
  ringbtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: textColor.white,
    paddingHorizontal: responsiveWidth(2),
    paddingVertical: responsiveWidth(1.5),
    borderRadius: responsiveWidth(5),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  logo: {
    height: responsiveHeight(9),
    width: responsiveWidth(22),
    resizeMode: "contain",
    marginRight: responsiveWidth(12),
  },
  ringbtnview: {
    flexDirection: "row",
  },
  bg: {
    height: responsiveHeight(42),
    width: responsiveWidth(60),
    // paddingLeft: responsiveWidth(3),
    justifyContent: "flex-end",
    // backgroundColor: "red",
  },
  bg1: {
    height: responsiveHeight(68),
    width: responsiveWidth(70),
    // paddingLeft: responsiveWidth(3),
    justifyContent: "flex-end",
    // backgroundColor: "red",
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 2,
    // },
    // shadowOpacity: 0.25,
    // shadowRadius: 3.84,

    // elevation: 5,
  },
  Modalbg3: {
    height: responsiveHeight(80),
    width: responsiveWidth(90),
    resizeMode: "contain",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: responsiveHeight(2),
    // backgroundColor: "transparent",
    // borderRadius:responsiveWidth(10),
    // marginLeft: responsiveWidth(5),
  },
  Modalbg2: {
    height: Platform.OS === "ios" ? responsiveHeight(90) : responsiveHeight(95),
    width: responsiveWidth(95),
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: Platform.OS === "ios" ? responsiveHeight(2) : null,

    // backgroundColor: "transparent",
    // borderRadius:responsiveWidth(10),
    // marginLeft: responsiveWidth(5),
  },
  Modalbg7: {
    height:
      Platform.OS === "android" ? responsiveHeight(87) : windowHeight * 0.9,
    width: Platform.OS === "android" ? responsiveWidth(95) : windowWidth * 0.95,
    // justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    // backgroundColor: "transparent",
    // borderRadius:responsiveWidth(10),
    // marginLeft: responsiveWidth(5),
  },
  Modalbg5: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",

    // borderRadius:responsiveWidth(10),
    // marginLeft: responsiveWidth(5),
  },
  Modal22: {
    height: responsiveHeight(100),
    width: responsiveWidth(100),
    backgroundColor: "rgba(0,0,0,0.8)",

    // backgroundColor: "red",
    // borderRadius:responsiveWidth(10),
    // marginLeft: responsiveWidth(5),
  },
  Modalbg: {
    height: responsiveHeight(100),
    width: responsiveWidth(100),
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",

    // backgroundColor: "red",
    // borderRadius:responsiveWidth(10),
    // marginLeft: responsiveWidth(5),
  },
  name: {
    fontSize: responsiveFontSize(4),
    color: textColor.white,
    fontFamily: fontFamily.appTextBold,
  },
  age: {
    fontSize: responsiveFontSize(3),
    color: textColor.white,
    fontFamily: fontFamily.appTextBold,
  },
  circlebtn2: {
    height: responsiveWidth(20),
    width: responsiveWidth(20),
    borderRadius: responsiveWidth(20 / 2),
    alignItems: "center",
    justifyContent: "center",
    marginTop: Platform.OS === "ios" ? responsiveHeight(1.5) : null,
    top: Platform.OS === "ios" ? responsiveHeight(1) : windowHeight * 0.02,
  },
  circlebtn: {
    height: responsiveWidth(20),
    width: responsiveWidth(20),
    borderRadius: responsiveWidth(20 / 2),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: textColor.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  circlecard2: {
    height: "62%",
    // backgroundColor:'green',
    width: responsiveWidth(35),

    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    position: "absolute",
    paddingHorizontal: responsiveWidth(2),
  },
  circlecard3: {
    height: "62%",
    width: responsiveWidth(35),
    // backgroundColor:'red',
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    position: "absolute",
    right: 0,
    paddingHorizontal: responsiveWidth(2),
  },
  placeholderView: {
    height: responsiveWidth(20),
    width: responsiveWidth(20),
    borderRadius: responsiveWidth(20 / 2),
    position: "absolute",

    bottom: responsiveHeight(10),
    // left: responsiveWidth(20),
    left: "35%",

    backgroundColor: "rgba(53,95,116,0.7)",
  },
  btnview: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: responsiveWidth(80),
    alignSelf: "center",
    alignItems: "center",
    // backgroundColor:'red'
    // marginTop: Platform.OS === 'ios' ? responsiveHeight(2.8):responsiveHeight(3),
  },
  topbar: {
    // flexDirection: "row",
    // alignItems: "center",
    justifyContent: "space-between",
    width: responsiveWidth(90),
    alignSelf: "center",
    marginTop: Platform.OS === "ios" ? responsiveHeight(4) : 0,
  },
  Carousel: {
    marginTop: responsiveHeight(4),
  },
  samllcircle: {
    height: responsiveWidth(10),
    width: responsiveWidth(10),
    borderRadius: responsiveWidth(10 / 2),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: textColor.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  samllcircle432: {
    height: responsiveWidth(10),
    width: responsiveWidth(10),
    borderRadius: responsiveWidth(10 / 2),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: textColor.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    // marginLeft:responsiveWidth(48),
    // marginTop:responsiveHeight(3)
  },
  samllcircle11: {
    height: responsiveWidth(10),
    width: responsiveWidth(10),
    borderRadius: responsiveWidth(10 / 2),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: textColor.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    // elevation: 1,
  },
  txt: {
    color: textColor.secondary,
    fontFamily: fontFamily.appTextBold,
    marginLeft: responsiveWidth(3),
    fontSize: responsiveFontSize(2),
    textAlign: "center",
  },
  boostModalView: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    height: responsiveHeight(20),
  },
  boostTxt2: {
    width: responsiveWidth(70),
    marginTop: responsiveHeight(3),
    alignSelf: "center",
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2.5),
    textAlign: "center",
  },
  boostTxt: {
    width: responsiveWidth(80),
    height: responsiveHeight(15),
    bottom: responsiveHeight(4),
    // backgroundColor:'green',
    // alignSelf: "center",
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2.3),
    textAlign: "center",
  },
  boostTxt2: {
    width: responsiveWidth(60),
    marginTop: responsiveWidth(35),
    alignSelf: "center",
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2.5),
    textAlign: "center",
    marginBottom: responsiveHeight(3),
  },
  boostTxt3: {
    width: responsiveWidth(60),
    marginTop: responsiveWidth(5),
    alignSelf: "center",
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(2.5),
    textAlign: "center",
    marginBottom: responsiveHeight(3),
  },
  btnGroup: {
    width: "95%",
    alignSelf: "center",
    // backgroundColor: "yellow",
    position: "absolute",
    // bottom: r(10.3),
    top: Platform.OS === "android" ? windowHeight * 0.58 : windowHeight * 0.54,
    justifyContent: "center",
  },
  btnGroupBoost: {
    flexDirection: "row",
    width: responsiveWidth(90),
    alignSelf: "center",
    // backgroundColor: "red",

    justifyContent: "center",
    marginTop: responsiveHeight(5),
  },
  noBtn: {
    width: responsiveWidth(70),
    height: responsiveHeight(8),
    // backgroundColor:'red',
    bottom: responsiveHeight(0.3),
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: responsiveWidth(5),
  },
  yesBtn: {
    backgroundColor: textColor.secondary,
    width: "70%",
    height: responsiveHeight(7),
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    borderRadius: responsiveWidth(5),
  },
  yesBtn1: {
    backgroundColor: textColor.secondary,
    width: responsiveWidth(60),
    height: responsiveHeight(6),
    justifyContent: "center",
    alignItems: "center",
    // marginRight: responsiveWidth(3),
    borderRadius: responsiveWidth(5),
  },
  yesTxt: {
    fontFamily: fontFamily.appTextMedium,
    color: "white",
    fontSize: responsiveFontSize(2.4),
  },
  noTxt: {
    fontFamily: fontFamily.appTextMedium,
    color: "#8c8c8c",
    fontSize: responsiveFontSize(2.2),
  },
  boostTimerTxt: {
    fontFamily: fontFamily.appTextBold,
    fontSize: responsiveFontSize(5),
    marginTop: responsiveHeight(10),
  },
  iconText: {
    fontFamily: fontFamily.appTextBold,
    color: textColor.secondary,
    marginTop: responsiveHeight(1),
    color: "#8c8c8c",
    textTransform: "uppercase",
  },
  iconSet: {
    flexDirection: "row",
    justifyContent: "space-between",
    // backgroundColor: "red",
    width: responsiveWidth(60),
    marginTop: responsiveHeight(5),
  },
  iconImage: {
    height: responsiveWidth(38),
    width: responsiveWidth(38),
    // marginTop: responsiveHeight(2),
    // left: responsiveWidth(5),
    zIndex: 1000,
    borderWidth: responsiveWidth(0.5),
    borderColor: textColor.white,
    borderRadius: responsiveWidth(38 / 2),
  },
  contdBtn: {
    height: responsiveWidth(20),
    width: responsiveWidth(20),
    borderRadius: responsiveWidth(10),
    position: "absolute",
    bottom: responsiveHeight(47),
  },
  topIcons: {
    height: responsiveHeight(20),
    width: responsiveWidth(20),
    marginTop: responsiveHeight(2),
  },
  optionView: {
    backgroundColor: textColor.white,
    alignItems: "center",
    justifyContent: "center",
    width: responsiveWidth(9),
    height: responsiveWidth(9),
    borderRadius: responsiveWidth(9 / 2),
    // transform: [{ scaleY: 1.5 }],
    marginTop: responsiveHeight(0.5),
    position: "absolute",
    // right: responsiveWidth(5),
    // top: responsiveHeight(3),
    alignSelf: "flex-end",
  },
  ringButton: {
    alignItems: "center",
    backgroundColor: textColor.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    justifyContent: "center",
    flexDirection: "row",
    height: responsiveHeight(5),
    width: responsiveHeight(5),
    borderRadius: responsiveHeight(10) / 2,
    zIndex: 10,
    position: "absolute",
    top: responsiveHeight(75),
    left: responsiveWidth(53),
  },
  boostButton: {
    alignItems: "center",
    backgroundColor: textColor.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    justifyContent: "center",
    flexDirection: "row",
    height: responsiveWidth(10),
    width: responsiveWidth(10),
    borderRadius: responsiveWidth(10 / 2),
    // position: "absolute",
    // top: responsiveHeight(75),
    alignSelf: "center",
    marginTop: responsiveHeight(5),
    right: responsiveWidth(6),
  },
  cardHeader: {
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    top: 0,
    alignSelf: "center",
    // backgroundColor: "rgba(0,0,0,0.5)",
    width: responsiveWidth(60),
    borderTopLeftRadius: responsiveWidth(3),
    borderTopRightRadius: responsiveWidth(3),
  },
  detailsview: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: responsiveWidth(3),
  },
  nametxt: {
    // textAlign: "center",
    fontSize: responsiveFontSize(2),
    fontFamily: fontFamily.appTextBold,
    color: textColor.white,
    // marginTop: responsiveHeight(1),
    bottom: responsiveHeight(0.22),
  },
});
